# Generated by Django 3.2.16 on 2023-01-23 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('is_staffed', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female'), ('d', 'Diverse'), ('x', 'None')], max_length=10, null=True)),
                ('salary', models.IntegerField()),
                ('start_date', models.DateField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personnel.department')),
            ],
            options={
                'ordering': ('last_name', 'first_name'),
            },
        ),
    ]
