# Generated by Django 3.2.16 on 2023-01-23 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
