# Generated by Django 3.2.16 on 2023-01-24 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0003_alter_personnel_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personnel',
            old_name='is_staffed',
            new_name='is_staff',
        ),
    ]
